version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=AggiesR0ck$
    restart: always
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  
  db:
    image: mariadb:10.11
    container_name: gitea_db
    environment:
      - MYSQL_ROOT_PASSWORD=AggiesR0ck$
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=AggiesR0ck$
      - MYSQL_DATABASE=gitea
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
